# Generated by Django 5.0.4 on 2024-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('operator', models.CharField()),
                ('region', models.CharField()),
                ('territory', models.CharField()),
                ('inn', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
